
package app.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2.8
 * Fri Jun 04 15:51:35 EEST 2010
 * Generated source version: 2.2.8
 */

@XmlRootElement(name = "stergeStudent", namespace = "http://lab10/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stergeStudent", namespace = "http://lab10/")

public class StergeStudent {

    @XmlElement(name = "arg0")
    private app.Student arg0;

    public app.Student getArg0() {
        return this.arg0;
    }

    public void setArg0(app.Student newArg0)  {
        this.arg0 = newArg0;
    }

}

